version: '3.9'

services:
  django:
    build: .
    ports:
      - 8000:8000
    restart: "on-failure"
    network_mode: 'host'
    dns:
      - 8.8.8.8

  db:
    image: postgres:11-alpine

    environment:
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=pgsql
      - PGPORT=5432
      - POSTGRES_USER=postgres
    restart: "on-failure"
    ports:
      - 5432:5432