# Generated by Django 5.0.2 on 2024-03-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_details_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
